name: Test actions pipeline

on:
  pull_request:
    branches: ['main']

  push:
    branches: ['main', 'fix-get-tested-head-for-windows']

jobs:
  test:
    name: Test get-tested and setup-get-tested
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract tested GHC versions
        id: create-matrix
        uses: ./
        with:
          cabal-file: get-tested.cabal
          ubuntu-version: 'latest'
          macos-version: 'latest'

      - name: Output matrix
        shell: bash
        run: |
          jq '.' <<< '${{ steps.create-matrix.outputs.matrix }}'

      - name: Set up without options
        id: setup
        uses: ./setup-get-tested

      - name: Set up with explicit directory
        id: setup-with-directory
        uses: ./setup-get-tested
        with:
          directory: "my-bin-dir"

      - name: Check paths are executable
        if: ${{ matrix.os }} != "windows-latest"
        shell: bash
        run: |
          for p in "${{ steps.setup.outputs.path }}" "${{ steps.setup-with-directory.outputs.path }}"; do
            echo "$p"
            if [[ -x "$p" ]]; then
              echo "Is executable"
            else
              echo "Is NOT executable"
              exit 1
            fi
          done
